// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5iCnNE29DhQy3UqGtH4LdPcWk2DHSkA8',
    appId: '1:588381108980:web:26c7876628a4772973bca1',
    messagingSenderId: '588381108980',
    projectId: 'comfyspaceauth-f01ef',
    authDomain: 'comfyspaceauth-f01ef.firebaseapp.com',
    storageBucket: 'comfyspaceauth-f01ef.appspot.com',
    measurementId: 'G-RXRX9YJPLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6z65_nDhM3nBxZgpl_3LzPbNnFkLxpN8',
    appId: '1:588381108980:android:39f003d8e0a49a8b73bca1',
    messagingSenderId: '588381108980',
    projectId: 'comfyspaceauth-f01ef',
    storageBucket: 'comfyspaceauth-f01ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzAmpGmrvY-5D2412H6iS7slyryQQf-g',
    appId: '1:588381108980:ios:47de1fd7c03ce25573bca1',
    messagingSenderId: '588381108980',
    projectId: 'comfyspaceauth-f01ef',
    storageBucket: 'comfyspaceauth-f01ef.appspot.com',
    androidClientId: '588381108980-s07bpcmaum5for3nplkckpc3r59a8usq.apps.googleusercontent.com',
    iosClientId: '588381108980-prkj2ljsnoap6q00b6heuj66kd3lad1e.apps.googleusercontent.com',
    iosBundleId: 'tech.comfystudio.comfyspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzAmpGmrvY-5D2412H6iS7slyryQQf-g',
    appId: '1:588381108980:ios:09847bb049a14a8073bca1',
    messagingSenderId: '588381108980',
    projectId: 'comfyspaceauth-f01ef',
    storageBucket: 'comfyspaceauth-f01ef.appspot.com',
    androidClientId: '588381108980-s07bpcmaum5for3nplkckpc3r59a8usq.apps.googleusercontent.com',
    iosClientId: '588381108980-k15q3hnbms2gasm9gd7jtt82f12uithn.apps.googleusercontent.com',
    iosBundleId: 'tech.comfyStudio.comfyspace.RunnerTests',
  );
}
